// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVkYxoA_49sZ93bINF0QYp1YSJQ-qa4OE',
    appId: '1:919787549248:web:50ee3bce187247fb6465a5',
    messagingSenderId: '919787549248',
    projectId: 'uv-tracker-113a7',
    authDomain: 'uv-tracker-113a7.firebaseapp.com',
    storageBucket: 'uv-tracker-113a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9z-yXktvOswnCpKUz79ZpynX3z29LVgw',
    appId: '1:919787549248:android:4f388aca1ab0a0fb6465a5',
    messagingSenderId: '919787549248',
    projectId: 'uv-tracker-113a7',
    storageBucket: 'uv-tracker-113a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl3ozxXHqHF9fX9eWrISihDqeXswA0u2I',
    appId: '1:919787549248:ios:420f5ea6a57dd7a56465a5',
    messagingSenderId: '919787549248',
    projectId: 'uv-tracker-113a7',
    storageBucket: 'uv-tracker-113a7.firebasestorage.app',
    iosClientId: '919787549248-n57i0667av0kq56rnl2cttk6uv454690.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl3ozxXHqHF9fX9eWrISihDqeXswA0u2I',
    appId: '1:919787549248:ios:420f5ea6a57dd7a56465a5',
    messagingSenderId: '919787549248',
    projectId: 'uv-tracker-113a7',
    storageBucket: 'uv-tracker-113a7.firebasestorage.app',
    iosClientId: '919787549248-n57i0667av0kq56rnl2cttk6uv454690.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVkYxoA_49sZ93bINF0QYp1YSJQ-qa4OE',
    appId: '1:919787549248:web:b8343fbc19fa8de26465a5',
    messagingSenderId: '919787549248',
    projectId: 'uv-tracker-113a7',
    authDomain: 'uv-tracker-113a7.firebaseapp.com',
    storageBucket: 'uv-tracker-113a7.firebasestorage.app',
  );
}
